### ISSUE TITLE
sass-variable-loader can support sass @import

### ISSUE THREAD

**Issue by minowu** [nordnet/sass-variable-loader#9]

**Comment by iamstarkov** [comment]
can you publish minimum reproducible test case as github repo?

**Comment by azcn2503** [comment]
I am also having this issue. It is easy to repro:

**variables.scss**
```scss
$myColor: red;
```

**component.scss**
```scss
@import "./variables.scss";

.component {
  background-color: $myColor;
}
```

**component.js**
```js
// Fails to compile with error: Undefined variable: "$myColor"
import styleVars from "!!sass-variable-loader!./component.scss";

// This works, however
import styleVars from "!!sass-variable-loader!./variables.scss";
```

It seems that when looking in `component.scss`, it is not importing variables from `variables.scss`.
